# Form implementation generated from reading ui file 'calibrate_2.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CalibrationWindow2(object):
    def setupUi(self, CalibrationWindow2):
        CalibrationWindow2.setObjectName("CalibrationWindow2")
        CalibrationWindow2.resize(411, 181)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CalibrationWindow2.sizePolicy().hasHeightForWidth())
        CalibrationWindow2.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(CalibrationWindow2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.model_name = QtWidgets.QLabel(CalibrationWindow2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.model_name.setFont(font)
        self.model_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.model_name.setObjectName("model_name")
        self.verticalLayout.addWidget(self.model_name)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.parameter = QtWidgets.QLabel(CalibrationWindow2)
        self.parameter.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.parameter.setObjectName("parameter")
        self.horizontalLayout.addWidget(self.parameter)
        self.step = QtWidgets.QLabel(CalibrationWindow2)
        self.step.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.step.setObjectName("step")
        self.horizontalLayout.addWidget(self.step)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.progressBar = QtWidgets.QProgressBar(CalibrationWindow2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)

        self.retranslateUi(CalibrationWindow2)
        QtCore.QMetaObject.connectSlotsByName(CalibrationWindow2)

    def retranslateUi(self, CalibrationWindow2):
        _translate = QtCore.QCoreApplication.translate
        CalibrationWindow2.setWindowTitle(_translate("CalibrationWindow2", "Dialog"))
        self.model_name.setText(_translate("CalibrationWindow2", "TextLabel"))
        self.parameter.setText(_translate("CalibrationWindow2", "Parâmetro: 10 Unidade"))
        self.step.setText(_translate("CalibrationWindow2", "Passo: 1/1"))
